[STC-2] Users can reset their password
diging/scriptoocloud pull request #13
Opened 2020-10-16 21:17 UTC by jormsby2

Changed name of config file as mentioned in previous pull request

2020-10-19 17:47 UTC, jdamerow requested changes

2020-10-19 17:47 UTC, jdamerow commented on scriptoocloud/pom.xml
> + 		<email.tls></email.tls>
let's put default values in `tls` and `appName`; those will probably be the same for most installations.

2020-10-23 18:17 UTC, jdamerow commented
Make it so, Jenkins.

2020-10-23 18:34 UTC, jdamerow commented
It doesn't send an email on the server, does it send an email locally (fakeSMTP could be useful to test this)? @coder-aakash994 since you just had that issue, do you see anything obviously missing?

2020-10-23 20:37 UTC, jormsby2 commented
> It doesn't send an email on the server, does it send an email locally (fakeSMTP could be useful to test this)? @coder-aakash994 since you just had that issue, do you see anything obviously missing?

I think the issue is with tls. I used tls false in my settings.xml and was able to send emails to a smtp service at mailtrap.io . I put TLS true in server default properties because I thought it wouldn't be an issue, but it seems to be the problem.

2020-10-23 20:41 UTC, jdamerow commented
No, I'm pretty sure we need startTLS to be enabled. True should be correct.

2020-10-23 22:12 UTC, coder-aakash994 commented
I compared the code to what I had worked with on Cord, and the only difference was the request mapping for the controllers. The `PasswordResetRequestController ` uses `/reset` whereas the `ResetPasswordRequestController` in Cord uses `/reset/password/request`.  The same with ResetPasswordRequestSentController, the mapping seems to be different than what I used in cord-geo-explorer. I will debug the code and get back to you.

2020-11-09 14:39 UTC, jdamerow commented
Resolve conflicts please

2020-11-09 14:39 UTC, closed without merging